#!/bin/bash

# 时区，语言
ln -sf /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime
hwclock --systohc
sed -i '177s/.//' /etc/locale.gen
locale-gen
echo 'LANG=en_US.UTF-8' >> /etc/locale.conf

# 主机名和hosts文件
echo 'arch' >> /etc/hostname
echo -e '127.0.0.1\tlocalhost' >> /etc/hosts
echo '::1\t\tlocalhost' >> /etc/hosts
echo '127.0.1.1\tarch.localdomain arch' >> /etc/hosts

# 引导
pacman -S grub efibootmgr intel-ucode
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB --recheck
grub-mkconfig -o /boot/grub/grub.cfg

# 网络管理
pacman -S networkmanager
systemctl enable NetworkManager

# root密码
echo root:rootpwd | chpasswd

# 新用户
pacman -S sudo
useradd -m selene
echo selene:userpwd | chpasswd
echo 'selene ALL=(ALL) ALL' >> /etc/sudoers.d/selene


